-- =========================================================
--  MoodBooster – Interests seed data
--  Run once (after schema.sql) in Supabase SQL Editor, or:
--    psql $DATABASE_URL -f backend/src/db/seed_interests.sql
--  Safe to re-run: every INSERT uses ON CONFLICT DO NOTHING.
-- =========================================================

-- ---------- Mother Tongue (language) ----------
-- `metadata.routingSlug`, when present, is synced onto users.mother_tongue
-- by routes/interests.js and picks a native comedy-script branch in
-- aiService.js. Languages with no routingSlug fall back to the app's
-- existing default (Tamil-script) humor style, unchanged.
INSERT INTO interest_items (category_key, name, aliases, metadata) VALUES
  ('mother_tongue', 'Tamil',              'tamil',                                  '{"routingSlug":"tamil"}'),
  ('mother_tongue', 'Tamil (Sri Lanka)',  'sri lankan tamil, eelam tamil',          '{"routingSlug":"tamil"}'),
  ('mother_tongue', 'Telugu',             'telugu',                                 '{"routingSlug":"telugu"}'),
  ('mother_tongue', 'Malayalam',          'malayalam, mallu',                       '{"routingSlug":"malayalam"}'),
  ('mother_tongue', 'Kannada',            'kannada',                                '{"routingSlug":"kannada"}'),
  ('mother_tongue', 'Hindi',              'hindi',                                  '{"routingSlug":"hindi"}'),
  ('mother_tongue', 'Hindi (Bhojpuri)',   'bhojpuri',                               '{"routingSlug":"hindi"}'),
  ('mother_tongue', 'Urdu',               'urdu',                                   '{"routingSlug":"hindi"}'),
  ('mother_tongue', 'English',            'english',                                '{"routingSlug":"english"}'),
  ('mother_tongue', 'English (UK)',       'british english',                        '{"routingSlug":"english"}'),
  ('mother_tongue', 'English (US)',       'american english',                       '{"routingSlug":"english"}'),
  ('mother_tongue', 'Bengali',            'bangla',                                 '{}'),
  ('mother_tongue', 'Marathi',            'marathi',                                '{}'),
  ('mother_tongue', 'Punjabi',            'panjabi',                                '{}'),
  ('mother_tongue', 'Gujarati',           'gujarati',                               '{}'),
  ('mother_tongue', 'Odia',               'oriya',                                  '{}'),
  ('mother_tongue', 'Assamese',           'assamese',                               '{}'),
  ('mother_tongue', 'Konkani',            'konkani',                                '{}'),
  ('mother_tongue', 'Sinhala',            'sinhalese',                              '{}'),
  ('mother_tongue', 'Nepali',             'nepali',                                 '{}'),
  ('mother_tongue', 'Spanish',            'espanol, castellano',                    '{}'),
  ('mother_tongue', 'French',             'francais',                               '{}'),
  ('mother_tongue', 'German',             'deutsch',                                '{}'),
  ('mother_tongue', 'Italian',            'italiano',                               '{}'),
  ('mother_tongue', 'Portuguese',         'portugues',                              '{}'),
  ('mother_tongue', 'Mandarin Chinese',   'mandarin, putonghua, chinese',           '{}'),
  ('mother_tongue', 'Cantonese',          'cantonese',                              '{}'),
  ('mother_tongue', 'Japanese',           'nihongo',                                '{}'),
  ('mother_tongue', 'Korean',             'hangugeo',                               '{}'),
  ('mother_tongue', 'Arabic',             'arabic, al-arabiya',                     '{}'),
  ('mother_tongue', 'Russian',            'russkiy',                                '{}'),
  ('mother_tongue', 'Indonesian',         'bahasa indonesia',                       '{}'),
  ('mother_tongue', 'Vietnamese',         'tieng viet',                             '{}'),
  ('mother_tongue', 'Thai',               'thai',                                   '{}'),
  ('mother_tongue', 'Filipino',           'tagalog, pilipino',                      '{}'),
  ('mother_tongue', 'Swahili',            'kiswahili',                              '{}'),
  ('mother_tongue', 'Turkish',            'turkce',                                 '{}')
ON CONFLICT (category_key, name) DO NOTHING;

-- ---------- Sport / Game ----------
INSERT INTO interest_items (category_key, name, aliases) VALUES
  ('sport', 'Cricket',                 NULL),
  ('sport', 'Indoor Cricket',          NULL),
  ('sport', 'Football (Soccer)',       'soccer, football'),
  ('sport', 'American Football',       'gridiron, nfl football'),
  ('sport', 'Footvolley',              NULL),
  ('sport', 'Basketball',              'nba'),
  ('sport', 'Baseball',                'mlb'),
  ('sport', 'Tennis',                  NULL),
  ('sport', 'Table Tennis',            'ping pong'),
  ('sport', 'Badminton',               NULL),
  ('sport', 'Volleyball',              NULL),
  ('sport', 'Beach Volleyball',        NULL),
  ('sport', 'Hockey (Field)',          'field hockey'),
  ('sport', 'Ice Hockey',              'nhl'),
  ('sport', 'Kabaddi',                 NULL),
  ('sport', 'Rugby',                   'rugby union, rugby league'),
  ('sport', 'Golf',                    NULL),
  ('sport', 'Boxing',                  NULL),
  ('sport', 'Mixed Martial Arts',      'mma, ufc'),
  ('sport', 'Wrestling',               NULL),
  ('sport', 'Swimming',                NULL),
  ('sport', 'Athletics (Track & Field)', 'track and field'),
  ('sport', 'Marathon Running',        'running'),
  ('sport', 'Cycling',                 NULL),
  ('sport', 'Formula 1',               'f1, motor racing'),
  ('sport', 'MotoGP',                  'motorcycle racing'),
  ('sport', 'Chess',                   NULL),
  ('sport', 'Carrom',                  NULL),
  ('sport', 'Snooker',                 'billiards, pool'),
  ('sport', 'Darts',                   NULL),
  ('sport', 'Archery',                 NULL),
  ('sport', 'Skateboarding',           NULL),
  ('sport', 'Surfing',                 NULL),
  ('sport', 'Skiing',                  NULL),
  ('sport', 'Snowboarding',            NULL),
  ('sport', 'Gymnastics',              NULL),
  ('sport', 'Weightlifting',           'powerlifting'),
  ('sport', 'Yoga',                    NULL),
  ('sport', 'Esports - FIFA',          'fifa, football games'),
  ('sport', 'Esports - Chess.com/Online Chess', 'online chess'),
  ('sport', 'Esports - Valorant',      'valorant'),
  ('sport', 'Esports - Dota 2',       'dota'),
  ('sport', 'Esports - League of Legends', 'lol, league'),
  ('sport', 'Handball',                NULL),
  ('sport', 'Squash',                  NULL),
  ('sport', 'Sepak Takraw',            NULL),
  ('sport', 'Polo',                    NULL),
  ('sport', 'Sailing',                 NULL),
  ('sport', 'Fencing',                 NULL)
ON CONFLICT (category_key, name) DO NOTHING;

-- ---------- Actor / Actress ----------
INSERT INTO interest_items (category_key, name, aliases) VALUES
  ('actor', 'Tom Cruise',             NULL),
  ('actor', 'Tom Hanks',              NULL),
  ('actor', 'Tom Holland',            NULL),
  ('actor', 'Leonardo DiCaprio',      'leo dicaprio'),
  ('actor', 'Brad Pitt',              NULL),
  ('actor', 'Robert Downey Jr.',      'rdj, iron man actor'),
  ('actor', 'Johnny Depp',            NULL),
  ('actor', 'Will Smith',             NULL),
  ('actor', 'Denzel Washington',      NULL),
  ('actor', 'Morgan Freeman',         NULL),
  ('actor', 'Keanu Reeves',           NULL),
  ('actor', 'Dwayne Johnson',         'the rock'),
  ('actor', 'Chris Hemsworth',        NULL),
  ('actor', 'Ryan Reynolds',          NULL),
  ('actor', 'Ryan Gosling',           NULL),
  ('actor', 'Matt Damon',             NULL),
  ('actor', 'Christian Bale',         NULL),
  ('actor', 'Hugh Jackman',           NULL),
  ('actor', 'Al Pacino',              NULL),
  ('actor', 'Robert De Niro',         NULL),
  ('actor', 'Samuel L. Jackson',      NULL),
  ('actor', 'George Clooney',         NULL),
  ('actor', 'Jennifer Lawrence',      NULL),
  ('actor', 'Scarlett Johansson',     NULL),
  ('actor', 'Emma Watson',            NULL),
  ('actor', 'Emma Stone',             NULL),
  ('actor', 'Meryl Streep',           NULL),
  ('actor', 'Angelina Jolie',         NULL),
  ('actor', 'Natalie Portman',        NULL),
  ('actor', 'Anne Hathaway',          NULL),
  ('actor', 'Margot Robbie',          NULL),
  ('actor', 'Zendaya',                NULL),
  ('actor', 'Priyanka Chopra',        'priyanka chopra jonas'),
  ('actor', 'Shah Rukh Khan',         'srk, king khan'),
  ('actor', 'Salman Khan',            NULL),
  ('actor', 'Aamir Khan',             NULL),
  ('actor', 'Amitabh Bachchan',       'big b'),
  ('actor', 'Ranveer Singh',          NULL),
  ('actor', 'Ranbir Kapoor',          NULL),
  ('actor', 'Hrithik Roshan',         NULL),
  ('actor', 'Deepika Padukone',       NULL),
  ('actor', 'Alia Bhatt',             NULL),
  ('actor', 'Kareena Kapoor',         'kareena kapoor khan'),
  ('actor', 'Katrina Kaif',           NULL),
  ('actor', 'Rajinikanth',            'thalaivar, superstar rajini'),
  ('actor', 'Kamal Haasan',           'ulaganayagan'),
  ('actor', 'Vijay',                  'thalapathy vijay'),
  ('actor', 'Ajith Kumar',            'thala ajith'),
  ('actor', 'Suriya',                 NULL),
  ('actor', 'Vikram',                 'chiyaan vikram'),
  ('actor', 'Dhanush',                NULL),
  ('actor', 'Vadivelu',               'vadivelu comedian'),
  ('actor', 'Vivek',                  'vivek comedian'),
  ('actor', 'Nayanthara',             'lady superstar'),
  ('actor', 'Trisha',                 'trisha krishnan'),
  ('actor', 'Prabhas',                'darling'),
  ('actor', 'Mahesh Babu',            'prince mahesh babu'),
  ('actor', 'Allu Arjun',             'bunny, stylish star'),
  ('actor', 'Jr NTR',                 'ntr junior'),
  ('actor', 'Ram Charan',             NULL),
  ('actor', 'Brahmanandam',           'brahmi'),
  ('actor', 'Mohanlal',               'lalettan, complete actor'),
  ('actor', 'Mammootty',              'mega star'),
  ('actor', 'Fahadh Faasil',          NULL),
  ('actor', 'Innocent',               'innocent actor'),
  ('actor', 'Suraj Venjaramoodu',     NULL),
  ('actor', 'Yash',                   'rocking star yash'),
  ('actor', 'Puneeth Rajkumar',       'appu, power star'),
  ('actor', 'Sadhu Kokila',           NULL),
  ('actor', 'Akshay Kumar',           NULL),
  ('actor', 'Ajay Devgn',             NULL),
  ('actor', 'Kapil Sharma',           NULL),
  ('actor', 'Johnny Lever',           NULL),
  ('actor', 'Zhang Ziyi',             NULL),
  ('actor', 'Jackie Chan',            NULL),
  ('actor', 'Song Kang-ho',           NULL),
  ('actor', 'Idris Elba',             NULL),
  ('actor', 'Cate Blanchett',         NULL),
  ('actor', 'Penelope Cruz',          NULL),
  ('actor', 'Antonio Banderas',       NULL)
ON CONFLICT (category_key, name) DO NOTHING;

-- ---------- Politician ----------
INSERT INTO interest_items (category_key, name, aliases) VALUES
  ('politician', 'Narendra Modi',        'modi, pm modi'),
  ('politician', 'Barack Obama',         NULL),
  ('politician', 'Joe Biden',            NULL),
  ('politician', 'Donald Trump',         NULL),
  ('politician', 'Kamala Harris',        NULL),
  ('politician', 'Rahul Gandhi',         NULL),
  ('politician', 'Amit Shah',            NULL),
  ('politician', 'Arvind Kejriwal',      NULL),
  ('politician', 'Mamata Banerjee',      NULL),
  ('politician', 'M. K. Stalin',         'mk stalin'),
  ('politician', 'J. Jayalalithaa',      'amma, jayalalithaa'),
  ('politician', 'M. Karunanidhi',       'kalaignar'),
  ('politician', 'Volodymyr Zelenskyy',  'zelensky'),
  ('politician', 'Vladimir Putin',       'putin'),
  ('politician', 'Xi Jinping',           NULL),
  ('politician', 'Justin Trudeau',       NULL),
  ('politician', 'Rishi Sunak',          NULL),
  ('politician', 'Keir Starmer',         NULL),
  ('politician', 'Boris Johnson',        NULL),
  ('politician', 'Emmanuel Macron',      NULL),
  ('politician', 'Olaf Scholz',          NULL),
  ('politician', 'Angela Merkel',        NULL),
  ('politician', 'Giorgia Meloni',       NULL),
  ('politician', 'Benjamin Netanyahu',   'netanyahu, bibi'),
  ('politician', 'Recep Tayyip Erdogan', 'erdogan'),
  ('politician', 'Imran Khan',           NULL),
  ('politician', 'Shehbaz Sharif',       NULL),
  ('politician', 'Sheikh Hasina',        NULL),
  ('politician', 'Muhammad Yunus',       NULL),
  ('politician', 'Anwar Ibrahim',        NULL),
  ('politician', 'Lee Hsien Loong',      NULL),
  ('politician', 'Fumio Kishida',        NULL),
  ('politician', 'Yoon Suk-yeol',        NULL),
  ('politician', 'Anthony Albanese',     NULL),
  ('politician', 'Jacinda Ardern',       NULL),
  ('politician', 'Nelson Mandela',       NULL),
  ('politician', 'Cyril Ramaphosa',      NULL),
  ('politician', 'Luiz Inacio Lula da Silva', 'lula'),
  ('politician', 'Javier Milei',         NULL),
  ('politician', 'Mahatma Gandhi',       'bapu, gandhi ji'),
  ('politician', 'Jawaharlal Nehru',     'nehru'),
  ('politician', 'Indira Gandhi',        NULL),
  ('politician', 'Abraham Lincoln',      NULL),
  ('politician', 'Winston Churchill',    NULL),
  ('politician', 'Nicolas Sarkozy',      NULL),
  ('politician', 'Droupadi Murmu',       'president murmu')
ON CONFLICT (category_key, name) DO NOTHING;

-- ---------- Business Leader ----------
INSERT INTO interest_items (category_key, name, aliases) VALUES
  ('business_leader', 'Elon Musk',           'tesla ceo, spacex ceo'),
  ('business_leader', 'Satya Nadella',       'microsoft ceo'),
  ('business_leader', 'Tim Cook',            'apple ceo'),
  ('business_leader', 'Sundar Pichai',       'google ceo, alphabet ceo'),
  ('business_leader', 'Jensen Huang',        'nvidia ceo'),
  ('business_leader', 'Jeff Bezos',          'amazon founder'),
  ('business_leader', 'Mark Zuckerberg',     'meta ceo, facebook founder'),
  ('business_leader', 'Bill Gates',          'microsoft founder'),
  ('business_leader', 'Warren Buffett',      'oracle of omaha'),
  ('business_leader', 'Larry Page',          'google co-founder'),
  ('business_leader', 'Sergey Brin',         'google co-founder'),
  ('business_leader', 'Sam Altman',          'openai ceo'),
  ('business_leader', 'Jack Ma',             'alibaba founder'),
  ('business_leader', 'Mukesh Ambani',       'reliance chairman'),
  ('business_leader', 'Gautam Adani',        'adani group chairman'),
  ('business_leader', 'Ratan Tata',          'tata group chairman emeritus'),
  ('business_leader', 'N. R. Narayana Murthy', 'infosys founder, narayana murthy'),
  ('business_leader', 'Kiran Mazumdar-Shaw', 'biocon founder'),
  ('business_leader', 'Falguni Nayar',       'nykaa founder'),
  ('business_leader', 'Byju Raveendran',     'byjus founder'),
  ('business_leader', 'Nikhil Kamath',       'zerodha co-founder'),
  ('business_leader', 'Nithin Kamath',       'zerodha ceo'),
  ('business_leader', 'Reid Hoffman',        'linkedin co-founder'),
  ('business_leader', 'Marc Benioff',        'salesforce ceo'),
  ('business_leader', 'Indra Nooyi',         'former pepsico ceo'),
  ('business_leader', 'Sheryl Sandberg',     'former meta coo'),
  ('business_leader', 'Steve Jobs',          'apple co-founder'),
  ('business_leader', 'Larry Ellison',       'oracle co-founder'),
  ('business_leader', 'Michael Dell',        'dell founder'),
  ('business_leader', 'Richard Branson',     'virgin group founder'),
  ('business_leader', 'Bernard Arnault',     'lvmh chairman'),
  ('business_leader', 'Jamie Dimon',         'jpmorgan ceo'),
  ('business_leader', 'Andy Jassy',          'amazon ceo'),
  ('business_leader', 'Lisa Su',             'amd ceo'),
  ('business_leader', 'Susan Wojcicki',      'former youtube ceo'),
  ('business_leader', 'Daniel Ek',           'spotify ceo'),
  ('business_leader', 'Brian Chesky',        'airbnb ceo'),
  ('business_leader', 'Travis Kalanick',     'uber co-founder'),
  ('business_leader', 'Anand Mahindra',      'mahindra group chairman'),
  ('business_leader', 'Kumar Mangalam Birla', 'aditya birla group chairman'),
  ('business_leader', 'Azim Premji',         'wipro founder chairman')
ON CONFLICT (category_key, name) DO NOTHING;
