import React from 'react';
import { useNavigate } from 'react-router-dom';
import TopBar from '../components/TopBar.jsx';

export default function Terms() {
  const navigate = useNavigate();
  return (
    <div className="max-w-md mx-auto pb-16">
      <TopBar title="Terms of Service" subtitle="Last updated June 2026" right={<BackBtn onClick={() => navigate(-1)} />} />
      <main className="px-5 pt-6 space-y-6 text-sm leading-relaxed text-ink">
        <Section title="What MoodBooster is">
          MoodBooster helps you turn small daily frustrations into a moment of humor, perspective, and
          one practical action. It's a lighthearted journaling tool, not a substitute for medical,
          psychological, or professional advice.
        </Section>

        <Section title="Not a crisis service">
          MoodBooster is not designed for situations involving self-harm, abuse, or mental health
          crises. If you're in crisis, please contact a local emergency service or a crisis
          helpline in your area.
        </Section>

        <Section title="Acceptable use">
          Don't use MoodBooster to submit content that targets a real, named private individual with
          harassment, hate speech, or threats. Community content should stay focused on everyday
          situations, not on identifying or attacking specific people.
        </Section>

        <Section title="AI-generated content">
          Humor, perspective, and action suggestions are generated by an AI model based on what
          you write. They're meant to be lighthearted and supportive - if a response ever feels
          off, you can skip sharing it, and it's never shown to anyone but you unless you choose
          to share it.
        </Section>

        <Section title="Your content">
          You own what you write. By sharing an entry anonymously, you grant MoodBooster a license to
          display the anonymized version in the Relatable feed. You can stop using the app and
          delete your account and data at any time.
        </Section>

        <Section title="Account responsibility">
          Keep your login credentials confidential. You're responsible for activity that happens
          under your account.
        </Section>

        <Section title="No warranty">
          MoodBooster is provided "as is." We do our best to keep the app reliable and the AI output
          appropriate, but we don't guarantee uninterrupted service or that every generated
          response will be perfect.
        </Section>

        <Section title="Changes to these terms">
          We may update these terms as the app evolves. Continued use after an update means you
          accept the revised terms.
        </Section>

        <Section title="Contact">
          Questions can be sent to support@moodbooster.app.
        </Section>
      </main>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <div>
      <h2 className="section-label mb-1">{title}</h2>
      <p className="text-inkSoft">{children}</p>
    </div>
  );
}

function BackBtn({ onClick }) {
  return (
    <button onClick={onClick} className="text-sm font-semibold text-slate-dark">
      Back
    </button>
  );
}
